# Generated by Django 3.2.25 on 2024-11-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
            ],
        ),
    ]
